Upstream Permutation struct into plonk::permutation
zcash/halo2 pull request #199
Opened 2021-02-18 11:48 UTC by therealyingtong

Closes #189

2021-02-18 23:42 UTC, ebfull requested changes
I should have been more specific in #189 about what I was desiring.

I want to change `ConstraintSystem` (in `crate::plonk::circuit`) so that it returns

```rust
pub fn permutation(&mut self, columns: &[Column<Any>]) -> Permutation {
```

and move the `Permutation` structure that currently exists in `src/circuit.rs` into `src/plonk/circuit.rs` where `ConstraintSystem` is defined.

Then, we can change the `Assignment` trait to do

```rust
    /// Assign two advice columns to have the same value
    fn copy(
        &mut self,
        permutation: Permutation,
        left_column: Column<Any>,
        left_row: usize,
        right_column: Column<Any>,
        right_row: usize,
    ) -> Result<(), Error>;
```

and so it's on the implementation of `Assignment` to figure out the index into the permutation's involved columns if it needs it. It can do that by scanning the vector inside of the `Permutation` structure. (This means that `Permutation` will need getters probably.)

Overall this simplifies the API so that downstream APIs don't need to care about "the permutation index" and the "column index inside the permutation" which are annoying things that can be screwed up easily.

2021-02-19 15:33 UTC, str4d commented on src/circuit.rs
> -pub struct Permutation {
I'm not sure that we want to move `Permutation` into `halo2::plonk::circuit`. Per #165 (where we want to get rid of `halo2::plonk::circuit`), the goal is for `halo2::circuit` to contain the types that most crate users (circuit implementors) deal with, while `halo2::plonk` contains the inner details that few people will use directly beyond `create_proof` and `verify_proof`.

2021-02-19 15:37 UTC, str4d commented on src/circuit.rs
> -pub struct Permutation {
Hmm, I now see that @ebfull suggested the move. I'm only weakly against it, so we can keep it as-is and then maybe move it back during #165.

2021-02-23 16:59 UTC, str4d approved these changes

2021-02-25 15:11 UTC, ebfull approved these changes

2021-02-25 15:24 UTC, merged