Change TGPPL references to BOSL
zcash/halo2 pull request #244
Opened 2021-04-16 15:40 UTC by steven-ecc

Updates all TGPPL references to BOSL and makes a few minor cleanups to wording.

2021-04-21 15:27 UTC, daira approved these changes
I have reservations about BOSL wrt license compatibility, but this PR does what it intends to do.

2021-04-26 22:10 UTC, ebfull requested changes

2021-04-26 22:10 UTC, ebfull commented on Cargo.toml
> +license = "BOSL"
```suggestion
license-file = "LICENSE-BOSL"
```

2021-04-26 23:44 UTC, merged

2021-04-27 01:02 UTC, gojomo commented
Is "BOSL" mainly a new name for "TGPPL"? (A search for `[bootstrap open source license]` mainly turns up info about the use of the MIT license by the JS/CSS UI project 'Bootstrap'.)

2021-04-27 01:24 UTC, steven-ecc commented
> Is "BOSL" mainly a new name for "TGPPL"? (A search for `[bootstrap open source license]` mainly turns up info about the use of the MIT license by the JS/CSS UI project 'Bootstrap'.)

That's correct for the most part Gordon. There's an additional requirement in BOSL that the source code for derived works be published prior to the derived work being made available but that was something we had planned to tweak in the TGPPL anyway.