Endoscaling instructions and chip
zcash/halo2 pull request #428
Opened 2021-12-13 14:56 UTC by therealyingtong

Partially closes #249.

Based on #473.

2021-12-30 17:46 UTC, ebfull requested changes

2022-01-21 13:54 UTC, str4d commented
This PR needs to be rebased, to now target `halo2/src`. Also I'd like to hold off merging this PR until we've cut `halo2 0.1.0-beta.2` removing all the old `halo2` content.

2022-03-10 13:07 UTC, daira commented on halo2/src/recursion/endoscale.rs
> +    /// this gadget.
```suggestion
    /// this gadget.
    ///
    /// Panics:
    /// * if `BITSTRING_NUM_BITS != WINDOW_NUM_BITS * NUM_WINDOWS`.
```

2022-03-18 16:35 UTC, therealyingtong commented on halo2/src/recursion/endoscale.rs
> +    fn endoscale_base<L: Layouter<C::Base>, const NUM_BITS: usize, const NUM_WINDOWS: usize>(
We possibly want `endoscale_fixed_base` (for public inputs) and `endoscale_var_base` (when multiplying by challenges).

2022-03-22 10:34 UTC, closed without merging