Release `halo2_proofs` and `halo2_gadgets` 0.1.0
zcash/halo2 pull request #581
Opened 2022-05-10 22:02 UTC by str4d

2022-05-10 22:04 UTC, ebfull requested changes
Still need to remove the "we're in beta and not audited" thing from the `halo2_gadgets` repo (you've just removed it from `halo2_proofs`)

2022-05-10 22:04 UTC, str4d commented
The only outdated dependency is `pprof`, which is less than a day old and is only a dev-dependency.

2022-05-10 22:07 UTC, ebfull approved these changes

2022-05-10 22:27 UTC, merged

2022-05-11 02:49 UTC, daira reviewed
Post-hoc utACK