Better lookup errors
zcash/halo2 pull request #755
Opened 2023-03-21 08:58 UTC by therealyingtong

"All good lookups are alike, but every bad lookup is bad in its own way" - @nalinbhardwaj

This is a more complete version of #750, inspired by https://github.com/zcash/halo2/pull/750#discussion_r1141000039.

2023-03-30 17:11 UTC, daira commented on halo2_proofs/src/circuit/layouter.rs
> -pub trait TableLayouter<F: Field>: fmt::Debug {
Let's re-export this here to reduce API breakage.

2023-03-30 17:16 UTC, ebfull requested changes

2023-03-30 17:16 UTC, ebfull commented on halo2_proofs/src/circuit.rs
> +pub mod table_layouter;
Let's keep this module private, so just `mod` I think.

2023-04-04 19:11 UTC, ebfull approved these changes

2023-04-04 23:08 UTC, daira commented on halo2_proofs/src/circuit/table_layouter.rs
> +    let column_lengths = column_lengths?;
```suggestion
        .collect()?;
```

2023-04-04 23:10 UTC, daira commented on halo2_proofs/src/circuit/table_layouter.rs
> +    let column_lengths: Result<Vec<_>, Error> = default_and_assigned
```suggestion
    let column_lengths = default_and_assigned
```

2023-04-04 23:25 UTC, daira approved these changes
utACK

2023-04-04 23:27 UTC, merged