Fix typo
zcash/halo2 pull request #782
Opened 2023-06-15 09:04 UTC by TomTaehoonKim

I fixed a typo in the halo2 book.

2023-06-16 10:49 UTC, TomTaehoonKim commented
@str4d @therealyingtong Review please!

2023-06-20 08:42 UTC, therealyingtong requested changes

2023-06-20 08:42 UTC, therealyingtong commented on book/src/design/proving-system/vanishing.md
> +At this point, all properties of the circuit have been committed to polynomials. The verifier now
```suggestion
At this point, we have committed to all properties of the circuit. The verifier now
```

2023-06-20 11:46 UTC, TomTaehoonKim commented on book/src/design/proving-system/vanishing.md
> +At this point, all properties of the circuit have been committed to polynomials. The verifier now
@therealyingtong Applied!

2023-06-27 17:21 UTC, therealyingtong approved these changes

2023-06-27 17:22 UTC, str4d approved these changes

2023-06-27 17:59 UTC, merged